version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai-chatbot-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

  minio:
    image: minio/minio:latest
    container_name: ai-chatbot-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    command: server /data --console-address ":9001"

  n8n:
    image: n8nio/n8n:latest
    container_name: ai-chatbot-n8n
    ports:
      - "5678:5678"
    volumes:
      - ./data/n8n:/home/node/.n8n
      - ./documents:/documents
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - WEBHOOK_URL=http://localhost:5678

  langfuse:
    image: langfuse/langfuse:latest
    container_name: ai-chatbot-langfuse
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://langfuse:password@langfuse-db:5432/langfuse
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - langfuse-db

  langfuse-db:
    image: postgres:15
    container_name: ai-chatbot-langfuse-db
    environment:
      - POSTGRES_USER=langfuse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=langfuse
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  qdrant_storage:
  minio_data:
  n8n_data:
  postgres_data: