version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: ai-chatbot-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    container_name: ai-chatbot-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  qdrant_storage:
  minio_data: